import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@app/styles/globals.css';

import WidthSidebarContextProvider from '@app/app/(dashboard)/user/context/WidthSidebarContext';
import PersonContextProvider from '@app/app/(dashboard)/user/context/PersonContext';
import UserContextProvider from '@app/app/(dashboard)/user/context/UserContext';

/**
 * Configuración de la fuente Roboto. (No se aplica por el momento)
 */
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    display: 'swap',
});

/**
 * Confinguración del SEO.
 */
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

/**
 * Layout principal de la app.
 * @param param0
 * @returns
 */
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <WidthSidebarContextProvider>
            <UserContextProvider>
                <PersonContextProvider>
                    <html lang="en">
                        <meta
                            name="viewport"
                            content="width=device-width, initial-scale=1.0"
                        />
                        <body className={''}>{children}</body>
                    </html>
                </PersonContextProvider>
            </UserContextProvider>
        </WidthSidebarContextProvider>
    );
}
