name: Quality - Scan - Frontend

on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    sonar:
        uses: zenwk-org/zenwk-workflows/.github/workflows/zenwk-quality-scan-nextjs-template.yml@main
        with:
            projectKey: zenwk-org_zenwk-frontend
            organization: zenwk-org
            projectDir: .
        secrets: inherit
